# Generated by Django 4.2 on 2023-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutimagemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
