# Generated by Django 4.2 on 2023-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_aboutpagemodel_image_aboutimagemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagemodel',
            options={'verbose_name': 'malumot', 'verbose_name_plural': 'malumotlar'},
        ),
        migrations.AlterModelOptions(
            name='indexfirstmodel',
            options={'verbose_name': 'sahifa', 'verbose_name_plural': 'sahifalar'},
        ),
        migrations.AddField(
            model_name='indexfirstmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexfirstmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
