# Generated by Django 4.2 on 2023-04-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_gallerymodel_galleryimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimagemodel',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='text',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
