# Generated by Django 4.2 on 2023-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_galleryimagemodel_text_alter_gallerymodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'ПРИЕМ В АКАДЕМИЧЕСКИЙ ЛИЦЕЙ',
                'verbose_name_plural': 'ПРИЕМ В АКАДЕМИЧЕСКИЙ ЛИЦЕЙ',
            },
        ),
    ]
