# Generated by Django 4.2 on 2023-04-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_lesson_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Togaraklar_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanlar_nomi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'круги',
                'verbose_name_plural': 'круги',
            },
        ),
        migrations.CreateModel(
            name='Togaraklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_raqami', models.CharField(max_length=255)),
                ('ustoz_f_i_sh', models.CharField(max_length=255)),
                ('togarak_vaqtlari', models.CharField(max_length=255)),
                ('togarak_xonasi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='togaraklar', to='my_app.togaraklar_category')),
            ],
        ),
    ]
