# Generated by Django 4.2 on 2023-04-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_togaraklar_category_togaraklar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanlar_nomi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.AlterModelOptions(
            name='togaraklar',
            options={'verbose_name': 'учителя кружка', 'verbose_name_plural': 'учителя кружка'},
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('files', models.FileField(upload_to='files/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='my_app.question_category')),
            ],
        ),
    ]
