# Generated by Django 4.2 on 2023-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_question_category_alter_togaraklar_options_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_category',
            options={'verbose_name': 'Задания category', 'verbose_name_plural': 'Задания category'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Задания teachers', 'verbose_name_plural': 'Задания teachers'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
