# Generated by Django 4.2 on 2023-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_question_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
