# Generated by Django 4.2 on 2023-04-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagemodel',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpagemodel',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpagemodel',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='achivments',
            name='achivment_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achivments',
            name='achivment_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achivments',
            name='achivment_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achivments',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achivments',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achivments',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='user_name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='user_name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='user_name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='galleryimagemodel',
            name='text_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='galleryimagemodel',
            name='text_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='galleryimagemodel',
            name='text_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='text_en',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='text_ru',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='text_uz',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='indexfirstmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexfirstmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexfirstmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='user_name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='user_name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='indexmiddlepage',
            name='user_name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='user_name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='user_name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='indexnewspage',
            name='user_name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='lavozm_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='lavozm_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='lavozm_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question_category',
            name='fanlar_nomi_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_category',
            name='fanlar_nomi_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_category',
            name='fanlar_nomi_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='author_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='author_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='author_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='title_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='result_reception',
            name='text_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='result_reception',
            name='text_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='result_reception',
            name='text_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='title_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rukavotstva',
            name='lavozm_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rukavotstva',
            name='lavozm_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rukavotstva',
            name='lavozm_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rukavotstva',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rukavotstva',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rukavotstva',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='togarak_vaqtlari_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='togarak_vaqtlari_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='togarak_vaqtlari_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='togarak_xonasi_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='togarak_xonasi_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='togarak_xonasi_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='ustoz_f_i_sh_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='ustoz_f_i_sh_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar',
            name='ustoz_f_i_sh_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar_category',
            name='fanlar_nomi_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar_category',
            name='fanlar_nomi_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='togaraklar_category',
            name='fanlar_nomi_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='user_name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='user_name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='yangliklarmodel',
            name='user_name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
